name: Appadvent

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: GitHub Code Checkout
        uses: actions/checkout@v4

      - name: Build and Deploy Local Container
        run: |
          docker build -t main-appadvent:latest .
          docker rm -f main-appadvent || true
          docker run -d \
            --name main-appadvent \
            --restart always \
            -p 3050:3000 \
            main-appadvent:latest
          docker image prune -f
